language: php

sudo: false

matrix:
  include:
    - php: 7.2
      env: VALIDATE_CODING_STYLE=true RUN_PHPSTAN=true IGNORE_PLATFORMS=false
    - php: 7.3
      env: VALIDATE_CODING_STYLE=false RUN_PHPSTAN=false IGNORE_PLATFORMS=true
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - travis_retry composer self-update

install:
  - if [ "$IGNORE_PLATFORMS" == "true" ]; then travis_retry composer update --no-interaction --prefer-source --ignore-platform-reqs; fi
  - if [ "$IGNORE_PLATFORMS" == "false" ]; then travis_retry composer update --no-interaction --prefer-source; fi

script:
  - composer tests

after_script:
  - if [ "$VALIDATE_CODING_STYLE" == "true" ]; then composer phpcs; fi
  - if [ "$RUN_PHPSTAN" == "true" ]; then composer phpstan; fi
